name: PR Close
on:
  pull_request:
    types: [closed]

concurrency:
  group: ${{ github.repository_id }}-pr-${{ github.event.pull_request.id }}

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version-file: ".nvmrc"
      - name: Install Dependencies
        run: yarn install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Install Pulumi
        uses: pulumi/actions@v4
      - name: Ensure stack is unlocked
        run: |
          pulumi login s3://stockitrf-pulumi
          (
            pulumi stack ls | grep "pr-${{ github.event.pull_request.id }}"
            if [ $? -eq 0 ]; then
              pulumi cancel -s "pr-${{ github.event.pull_request.id }}" -y --non-interactive
            fi
          ) || true
        working-directory: ./infrastructure
        env:
          PULUMI_CONFIG_PASSPHRASE_FILE: "./.passphrase"
      - name: Destroy Infrastructure
        uses: pulumi/actions@v4
        with:
          cloud-url: s3://stockitrf-pulumi
          command: destroy
          remove: true
          secrets-provider: "file://${{ github.workspace }}/infrastructure/.passphrase"
          stack-name: "pr-${{ github.event.pull_request.id }}"
          work-dir: ./infrastructure
        env:
          PULUMI_CONFIG_PASSPHRASE_FILE: "./.passphrase"
